#!/usr/bin/env ruby

require 'very_safe_rm'

file, args = VerySafeRm::Arg.parse ARGV

if args.include? '--version'
  print 'very_safe_rm '
  puts VerySafeRm::VERSION
  puts
  system '/bin/rm --version'
  exit
end

if args.include? '--help'
  system ['/bin/rm', $PROGRAM_NAME], '--help'
  exit
end

if file.empty?
  system ['/bin/rm', $PROGRAM_NAME]
  exit 1
end

if args.include?('-r') || args.include?('-R') || args.include?('--recursive')
  STDERR.print 'Did you really want to delete directory? [y/N] '
  exit unless STDIN.gets.chomp =~ /^y(es)?$/i
end

VerySafeRm.run file, args
