#!/usr/bin/env ruby

require 'very_safe_rm'

file, args = VerySafeRm.parse ARGV

if file.empty?
  system 'rm'
  exit
end

if args.include?('-r') || args.include?('-R') || args.include?('--recursive')
  STDERR.print 'Did you really want to delete directory? [y/N] '
  exit unless STDIN.gets.chomp =~ /^y(es)?$/i
end

VerySafeRm.run file, args
