#!/usr/bin/env ruby

require 'very_safe_rm'

file, args = VerySafeRm::Arg.parse ARGV

if args.include? '--version'
  print 'very_safe_rm '
  puts VerySafeRm::VERSION
  puts
  system 'rm --version'
  exit
end

if file.empty?
  system 'rm'
  exit 1
end

if args.include?('-r') || args.include?('-R') || args.include?('--recursive')
  STDERR.print 'Did you really want to delete directory? [y/N] '
  exit unless STDIN.gets.chomp =~ /^y(es)?$/i
  args << '-f'
end

VerySafeRm.run file, args
